# Generated by Django 4.2.14 on 2024-09-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_alter_store_code_alter_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'line',
                'verbose_name_plural': 'lines',
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productbrand', verbose_name='brand')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productfamily', verbose_name='family')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productline', verbose_name='line')),
                ('retail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeretail', verbose_name='retail')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
