# Generated by Django 4.2.14 on 2024-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor_productsize_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indicates whether this product is active. Uncheck this option if it is not active.', verbose_name='is active'),
        ),
    ]
