# Generated by Django 4.2.14 on 2024-09-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_is_covered'),
        ('products', '0008_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productline', verbose_name='line'),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.storeretail', verbose_name='retail'),
        ),
    ]
