# Generated by Django 4.2.14 on 2024-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='productline',
            constraint=models.UniqueConstraint(condition=models.Q(('name', '-'), _negated=True), fields=('name',), name='unique_name_not_dash'),
        ),
    ]
