# Generated by Django 4.2.14 on 2024-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productline_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_not_null',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('sku',), name='nombre único'),
        ),
    ]
