# Generated by Django 4.2.14 on 2024-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_unique_sku_not_null_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='nombre único',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('sku',), name='unique_sku_not_null'),
        ),
    ]
