# Generated by Django 4.2.14 on 2024-09-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_unique_sku_not_null_product_sku_único'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productline', verbose_name='line'),
        ),
    ]
