# Generated by Django 4.2.14 on 2024-09-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
