# Generated by Django 4.2.14 on 2024-09-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productline', verbose_name='line'),
            preserve_default=False,
        ),
    ]
