# Generated by Django 4.2.14 on 2024-09-12 07:10

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[products.models.validate_numeric_digits], verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[products.models.validate_three_digit_code], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='productfamily',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[products.models.validate_three_digit_code], verbose_name='code'),
        ),
    ]
