# Generated by Django 4.2.14 on 2024-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sale date'),
        ),
    ]
