# Generated by Django 4.2.14 on 2024-10-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesource', verbose_name='source'),
        ),
    ]
