# Generated by Django 4.2.14 on 2024-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=6, verbose_name='unit price'),
        ),
    ]
