# Generated by Django 4.2.14 on 2024-12-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_saledetail_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='unit price'),
        ),
    ]
