# Generated by Django 4.2.14 on 2024-12-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0006_alter_sale_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('client_last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('client_document_type', models.CharField(max_length=50, verbose_name='document type')),
                ('client_document', models.CharField(max_length=50, unique=True, verbose_name='document number')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('answer_1', models.TextField(blank=True, null=True, verbose_name='answer 1')),
                ('answer_2', models.TextField(blank=True, null=True, verbose_name='answer 2')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the client (optional)', null=True, upload_to='client_photos/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to='sales.sale', verbose_name='sale')),
            ],
            options={
                'verbose_name': 'personal data',
                'verbose_name_plural': 'personal data',
                'ordering': ['-created_at'],
            },
        ),
    ]
