# Generated by Django 4.2.14 on 2024-12-03 19:15

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_alter_personaldata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='client_document_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[utils.validators.validate_only_digits, django.core.validators.MinLengthValidator(9)], verbose_name='phone number'),
        ),
    ]
