# Generated by Django 4.2.14 on 2024-12-14 09:16

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_alter_personaldata_client_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='answer_1',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=3, verbose_name='Cuando usted llegó, ¿pensó en comprar Paraíso? '),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='answer_2',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=3, verbose_name='¿Podemos llamarlo/a en 3 semanas para hacerle algunas preguntas sobre su compra? '),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_document_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='client document number'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_document_type',
            field=models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('CE', 'Carnet de Extranjería')], max_length=3, verbose_name='client document type'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='client email'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_first_name',
            field=models.CharField(max_length=255, verbose_name='client first name'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_last_name',
            field=models.CharField(max_length=255, verbose_name='client last name'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='client_phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[utils.validators.validate_only_digits, django.core.validators.MinLengthValidator(9)], verbose_name='client phone number'),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='photo',
            field=models.ImageField(help_text='Photo of the personal data survey', upload_to='personal_data_survey_photos/', verbose_name='survey photo'),
        ),
    ]
