# Generated by Django 4.2.14 on 2024-09-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_address_options_alter_addresscity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='addresscity',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='addressdepartment',
            options={'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='addressdistrict',
            options={'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='addresszonegroup',
            options={'verbose_name': 'zonal group', 'verbose_name_plural': 'zonal groups'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.addressdistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='addresscity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='addresscity',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.addressdepartment', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='addresscity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='addressdepartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='addressdepartment',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='addressdistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.addresscity', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='addressdistrict',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='addressdistrict',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='addressdistrict',
            name='zone_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.addresszonegroup', verbose_name='zonal group'),
        ),
        migrations.AlterField(
            model_name='addresszonegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='addresszonegroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
