# Generated by Django 4.2.14 on 2024-09-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_address_options_alter_addresscity_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressZoneGroup',
            new_name='AddressZonalGroup',
        ),
        migrations.RenameField(
            model_name='addressdistrict',
            old_name='zone_group',
            new_name='zonal_group',
        ),
    ]
