# Generated by Django 4.2.14 on 2024-09-12 07:10

from django.db import migrations, models
import locations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_rename_addresszonegroup_addresszonalgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8, validators=[locations.validators.validate_latitude], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, validators=[locations.validators.validate_longitude], verbose_name='longitude'),
        ),
    ]
