# Generated by Django 4.2.14 on 2024-08-22 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='corporate_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corporate_device_imei',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IMEI de teléfono corporativo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corporate_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de teléfono corporativo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creación de registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=255, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de empleo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de empleo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Coordinador'),
        ),
    ]
