# Generated by Django 4.2.14 on 2024-09-03 08:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dni',
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_number',
            field=models.CharField(default=12345678, max_length=9, verbose_name='document number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería')], default='DNI', max_length=3, verbose_name='document type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corporate_device_imei',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='corporate device imei'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='corporate_phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='corporate phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='employment end'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employment_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='employment start'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='coordinator'),
        ),
    ]
