# Generated by Django 4.2.14 on 2024-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_remove_customuser_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='document number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'foreigner card')], max_length=3, verbose_name='document type'),
        ),
    ]
