# Generated by Django 4.2.14 on 2024-09-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
