# Generated by Django 4.2.14 on 2024-09-05 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_rename_addresszonegroup_addresszonalgroup_and_more'),
        ('users', '0006_delete_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address', verbose_name='address'),
        ),
    ]
