# Generated by Django 4.2.14 on 2024-09-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='supervisor',
            new_name='coordinator',
        ),
    ]
