# Generated by Django 4.2.14 on 2024-09-05 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 5, 1, 14, 21, 762974, tzinfo=datetime.timezone.utc), verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storechannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 5, 1, 14, 42, 846118, tzinfo=datetime.timezone.utc), verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storecoverage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 5, 1, 14, 47, 345711, tzinfo=datetime.timezone.utc), verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeretail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 5, 1, 14, 50, 191348, tzinfo=datetime.timezone.utc), verbose_name='created at'),
            preserve_default=False,
        ),
    ]
