# Generated by Django 4.2.14 on 2024-09-05 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_rename_addresszonegroup_addresszonalgroup_and_more'),
        ('stores', '0002_store_created_at_storechannel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storechannel',
            options={'verbose_name': 'channel', 'verbose_name_plural': 'channels'},
        ),
        migrations.AlterModelOptions(
            name='storecoverage',
            options={'verbose_name': 'coverage', 'verbose_name_plural': 'coverages'},
        ),
        migrations.AlterModelOptions(
            name='storeretail',
            options={'verbose_name': 'retail', 'verbose_name_plural': 'retails'},
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.address', verbose_name='address'),
        ),
    ]
