# Generated by Django 4.2.14 on 2024-09-06 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_remove_store_coverage_store_is_covered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_covered',
            field=models.BooleanField(default=False, help_text='Indicates whether this store is covered. Uncheck this option if it is not covered.', verbose_name='coverage'),
        ),
        migrations.AlterField(
            model_name='store',
            name='promoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='promoter_stores', to=settings.AUTH_USER_MODEL, verbose_name='promoters'),
        ),
    ]
