# Generated by Django 4.2.14 on 2024-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_is_covered_alter_store_promoters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
