# Generated by Django 4.2.14 on 2024-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_code_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_covered',
            field=models.BooleanField(default=True, help_text='Indicates whether this store is covered. Uncheck this option if it is not covered.', verbose_name='coverage'),
        ),
    ]
