# Generated by Django 4.2.14 on 2024-09-12 07:11

from django.db import migrations, models
import stores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_is_covered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeretail',
            name='code',
        ),
        migrations.AddField(
            model_name='storeretail',
            name='ruc',
            field=models.CharField(default='11111111111', max_length=11, validators=[stores.validators.validate_ruc], verbose_name='ruc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=6, unique=True, validators=[stores.validators.validate_alpha_numeric_code], verbose_name='code'),
        ),
    ]
