# Generated by Django 4.2.14 on 2024-09-12 07:42

from django.db import migrations, models
import stores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_storeretail_code_storeretail_ruc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeretail',
            name='code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='storeretail',
            name='ruc',
            field=models.CharField(max_length=11, unique=True, validators=[stores.validators.validate_ruc], verbose_name='RUC'),
        ),
    ]
