# Generated by Django 4.2.14 on 2024-09-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_storeretail_code_alter_storeretail_ruc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeretail',
            name='code',
        ),
    ]
