# Generated by Django 4.2.14 on 2024-09-12 08:01

from django.db import migrations, models
import stores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_storeretail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeretail',
            name='ruc',
            field=models.CharField(max_length=11, validators=[stores.validators.validate_ruc], verbose_name='RUC'),
        ),
    ]
