# Generated by Django 4.2.14 on 2024-09-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_store_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='code',
        ),
    ]
