# Generated by Django 4.2.14 on 2024-11-27 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0013_remove_store_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='promoters',
            field=models.ManyToManyField(blank=True, related_name='promoter_stores', to=settings.AUTH_USER_MODEL, verbose_name='promoters'),
        ),
    ]
