# Generated by Django 4.2.14 on 2024-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_alter_store_promoters'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='code'),
        ),
    ]
