# Generated by Django 4.2.14 on 2024-12-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(help_text='Photo of the user marking attendance', upload_to='attendance_photos/', verbose_name='photo'),
        ),
    ]
