"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os, sys
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Agrega la carpeta 'apps' al sistema de módulos
sys.path.insert(0, str(BASE_DIR / 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.18.52',
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'unfold.contrib.guardian',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_admin_listfilter_dropdown',

    'apps.users',
    'apps.locations', 
    'apps.stores',
    'apps.products',
    'apps.sales',
    'apps.attendances',
    'apps.personal_data',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_L10N = False # Date format

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / "static"]

#STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

UNFOLD = {
    'SITE_TITLE': 'Below Admin',
    'SITE_HEADER': 'Paraiso Admin',
    'SITE_URL': '/',
    'SITE_ICON': {
        'light': lambda request: static('images/below-light.png'),
        'dark': lambda request: static('images/below-dark.png'),
    },
    'SITE_SYMBOL': 'dashboard',
    'SITE_FAVICONS': [
        {
            'rel': 'icon',
            'sizes': '32x32',
            'type': 'image/svg+xml',
            'href': lambda request: static('favicon.svg'),
        },
    ],
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': False,
    'ENVIRONMENT': 'api.utils.environment_callback',
    'LOGIN': {
        #'image': lambda request: static('sample/login-bg.jpg'),
        #'redirect_after': lambda request: reverse_lazy('admin:APP_MODEL_changelist'),
    },
    'STYLES': [
        lambda request: static('css/style.css'),
    ],
    'SCRIPTS': [
        lambda request: static('js/script.js'),
    ],
    'COLORS': {
        'primary': {
            '50': '255 248 240',
            '100': '255 233 212',
            '200': '255 210 173',
            '300': '255 184 117',
            '400': '255 149 58',
            '500': '255 120 10',
            '600': '234 108 9',
            '700': '206 94 8',
            '800': '168 77 7',
            '900': '135 62 5',
            '950': '100 45 3',
        },
    },
    'EXTENSIONS': {
        'modeltranslation': {
            'flags': {
                'es': '🇪🇸',
                'en': '🇬🇧',
            },
        },
    },
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': _('Personal data'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Personal data form'),
                        'icon': 'perm_contact_calendar',
                        'link': reverse_lazy('admin:personal_data_personaldata_changelist'),
                    },
                ],
            },
            {
                'title': _('Attendances'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Attendance record types'),
                        'icon': 'door_open',
                        'link': reverse_lazy('admin:attendances_attendancerecordtype_changelist'),
                    },
                    {
                        'title': _('Attendance access type'),
                        'icon': 'switch_access_2',
                        'link': reverse_lazy('admin:attendances_attendanceaccesstype_changelist'),
                    },
                    {
                        'title': _('Attendances'),
                        'icon': 'familiar_face_and_zone',
                        'link': reverse_lazy('admin:attendances_attendance_changelist'),
                    },
                ],
            },
            {
                'title': _('Sales'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Types'),
                        'icon': 'sell',
                        'link': reverse_lazy('admin:sales_saletype_changelist'),
                    },
                    {
                        'title': _('Sources'),
                        'icon': 'cloud_download',
                        'link': reverse_lazy('admin:sales_salesource_changelist'),
                    },
                    {
                        'title': _('Statuses'),
                        'icon': 'published_with_changes',
                        'link': reverse_lazy('admin:sales_salestatus_changelist'),
                    },
                    {
                        'title': _('Price types'),
                        'icon': 'credit_card',
                        'link': reverse_lazy('admin:sales_salepricetype_changelist'),
                    },
                    {
                        'title': _('Sales'),
                        'icon': 'shopping_cart',
                        'link': reverse_lazy('admin:sales_sale_changelist'),
                    },
                ],
            },
            {
                'title': _('Products'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Groups'),
                        'icon': 'category',
                        'link': reverse_lazy('admin:products_productgroup_changelist'),
                    },
                    {
                        'title': _('Families'),
                        'icon': 'family_history',
                        'link': reverse_lazy('admin:products_productfamily_changelist'),
                    },
                    {
                        'title': _('Brands'),
                        'icon': 'hub',
                        'link': reverse_lazy('admin:products_productbrand_changelist'),
                    },
                    {
                        'title': _('Lines'),
                        'icon': 'account_tree',
                        'link': reverse_lazy('admin:products_productline_changelist'),
                    },
                    {
                        'title': _('Sizes'),
                        'icon': 'straighten',
                        'link': reverse_lazy('admin:products_productsize_changelist'),
                    },
                    {
                        'title': _('Colors'),
                        'icon': 'palette',
                        'link': reverse_lazy('admin:products_productcolor_changelist'),
                    },
                    {
                        'title': _('Products'),
                        'icon': 'barcode_scanner',
                        'link': reverse_lazy('admin:products_product_changelist'),
                    },
                ],
            },
            {
                'title': _('Stores'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Channels'),
                        'icon': 'tenancy',
                        'link': reverse_lazy('admin:stores_storechannel_changelist'),
                    },
                    {
                        'title': _('Retails'),
                        'icon': 'storefront',
                        'link': reverse_lazy('admin:stores_storeretail_changelist'),
                    },     
                    {
                        'title': _('Stores'),
                        'icon': 'store',
                        'link': reverse_lazy('admin:stores_store_changelist'),
                    },
                ],
            },
            {
                'title': _('Locations'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Departments'),
                        'icon': 'south_america',
                        'link': reverse_lazy('admin:locations_addressdepartment_changelist'),
                    },
                    {
                        'title': _('Cities'),
                        'icon': 'emoji_transportation',
                        'link': reverse_lazy('admin:locations_addresscity_changelist'),
                    },
                    {
                        'title': _('Districts'),
                        'icon': 'home_work',
                        'link': reverse_lazy('admin:locations_addressdistrict_changelist'),
                    },
                    {
                        'title': _('Zonal groups'),
                        'icon': 'explore',
                        'link': reverse_lazy('admin:locations_addresszonalgroup_changelist'),
                    },
                    {
                        'title': _('Addresses'),
                        'icon': 'pin_drop',
                        'link': reverse_lazy('admin:locations_address_changelist'),
                    },
                ],
            },
            {
                'title': _('Users & Groups'),
                'collapsible': True,
                'items': [
                    {
                        'title': _('Users'),
                        'icon': 'person',
                        'link': reverse_lazy('admin:users_customuser_changelist'),
                    },
                    {
                        'title': _('Groups'),
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                    },
                ],
            },
            
        ],
    },
}